name: dashboard_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  lottie: ^3.0.0
  hexcolor: ^3.0.1
  intl: ^0.20.2
  http: ^1.4.0
  get: ^4.7.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.4.0
  flutter_timezone: ^4.1.1
  url_launcher: ^6.2.5
  flutter_phone_direct_caller: ^2.1.1
  image_picker: ^1.1.2
  path_provider: ^2.0.11 
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.1
  flutter_riverpod: ^2.4.5
  fl_chart: ^1.0.0
  syncfusion_flutter_pdfviewer: ^30.1.42
  open_file: ^3.5.10
  flutter_pdfview: ^1.3.2
  share_plus: ^10.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 500
